# TCL File Generated by Component Editor 20.1
# Sun Apr 11 18:17:13 EDT 2021
# DO NOT MODIFY


# 
# dma_engine "DMA Engine" v1.0
#  2021.04.11.18:17:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dma_engine
# 
set_module_property DESCRIPTION ""
set_module_property NAME dma_engine
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "DMA Engine"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dma_engine
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dma_engine.v VERILOG PATH src/ppu/dma_engine/dma_engine.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dma_engine
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dma_engine.v VERILOG PATH src/ppu/dma_engine/dma_engine.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset system_reset_n reset_n Input 1


# 
# connection point read_master
# 
add_interface read_master avalon start
set_interface_property read_master addressUnits SYMBOLS
set_interface_property read_master associatedClock clk
set_interface_property read_master associatedReset reset
set_interface_property read_master bitsPerSymbol 8
set_interface_property read_master burstOnBurstBoundariesOnly false
set_interface_property read_master burstcountUnits WORDS
set_interface_property read_master doStreamReads false
set_interface_property read_master doStreamWrites false
set_interface_property read_master holdTime 0
set_interface_property read_master linewrapBursts false
set_interface_property read_master maximumPendingReadTransactions 0
set_interface_property read_master maximumPendingWriteTransactions 0
set_interface_property read_master readLatency 0
set_interface_property read_master readWaitTime 1
set_interface_property read_master setupTime 0
set_interface_property read_master timingUnits Cycles
set_interface_property read_master writeWaitTime 0
set_interface_property read_master ENABLED true
set_interface_property read_master EXPORT_OF ""
set_interface_property read_master PORT_NAME_MAP ""
set_interface_property read_master CMSIS_SVD_VARIABLES ""
set_interface_property read_master SVD_ADDRESS_GROUP ""

add_interface_port read_master read_address address Output 32
add_interface_port read_master read_chipselect chipselect Output 1
add_interface_port read_master read_read_n read_n Output 1
add_interface_port read_master read_readdata readdata Input 128
add_interface_port read_master read_readdatavalid readdatavalid Input 1
add_interface_port read_master read_waitrequest waitrequest Input 1


# 
# connection point write_master
# 
add_interface write_master avalon start
set_interface_property write_master addressUnits SYMBOLS
set_interface_property write_master associatedClock clk
set_interface_property write_master associatedReset reset
set_interface_property write_master bitsPerSymbol 8
set_interface_property write_master burstOnBurstBoundariesOnly false
set_interface_property write_master burstcountUnits WORDS
set_interface_property write_master doStreamReads false
set_interface_property write_master doStreamWrites false
set_interface_property write_master holdTime 0
set_interface_property write_master linewrapBursts false
set_interface_property write_master maximumPendingReadTransactions 0
set_interface_property write_master maximumPendingWriteTransactions 0
set_interface_property write_master readLatency 0
set_interface_property write_master readWaitTime 1
set_interface_property write_master setupTime 0
set_interface_property write_master timingUnits Cycles
set_interface_property write_master writeWaitTime 0
set_interface_property write_master ENABLED true
set_interface_property write_master EXPORT_OF ""
set_interface_property write_master PORT_NAME_MAP ""
set_interface_property write_master CMSIS_SVD_VARIABLES ""
set_interface_property write_master SVD_ADDRESS_GROUP ""

add_interface_port write_master write_address address Output 16
add_interface_port write_master write_byteenable byteenable Output 16
add_interface_port write_master write_chipselect chipselect Output 1
add_interface_port write_master write_write_n write_n Output 1
add_interface_port write_master write_writedata writedata Output 128
add_interface_port write_master write_waitrequest waitrequest Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clk
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end dma_engine_src_addr src_addr Input 32
add_interface_port conduit_end dma_engine_start start Input 1
add_interface_port conduit_end dma_engine_finish finish Output 1

