# TCL File Generated by Component Editor 20.1
# Sun Apr 11 18:16:26 EDT 2021
# DO NOT MODIFY


# 
# pio_write_w_avail "PIO for those who are absolutely bonkers" v1.0
#  2021.04.11.18:16:26
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pio_write_w_avail
# 
set_module_property DESCRIPTION ""
set_module_property NAME pio_write_w_avail
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "PIO for those who are absolutely bonkers"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pio_write_w_avail
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pio_write_w_avail.sv SYSTEM_VERILOG PATH src/pio_write_w_avail.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pio_write_w_avail
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file pio_write_w_avail.sv SYSTEM_VERILOG PATH src/pio_write_w_avail.sv


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH WIDTH ""
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point avalon_writeable_slave
# 
add_interface avalon_writeable_slave avalon end
set_interface_property avalon_writeable_slave addressUnits WORDS
set_interface_property avalon_writeable_slave associatedClock clock
set_interface_property avalon_writeable_slave associatedReset reset
set_interface_property avalon_writeable_slave bitsPerSymbol 8
set_interface_property avalon_writeable_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_writeable_slave burstcountUnits WORDS
set_interface_property avalon_writeable_slave explicitAddressSpan 0
set_interface_property avalon_writeable_slave holdTime 0
set_interface_property avalon_writeable_slave linewrapBursts false
set_interface_property avalon_writeable_slave maximumPendingReadTransactions 0
set_interface_property avalon_writeable_slave maximumPendingWriteTransactions 0
set_interface_property avalon_writeable_slave readLatency 0
set_interface_property avalon_writeable_slave readWaitTime 1
set_interface_property avalon_writeable_slave setupTime 0
set_interface_property avalon_writeable_slave timingUnits Cycles
set_interface_property avalon_writeable_slave writeWaitTime 0
set_interface_property avalon_writeable_slave ENABLED true
set_interface_property avalon_writeable_slave EXPORT_OF ""
set_interface_property avalon_writeable_slave PORT_NAME_MAP ""
set_interface_property avalon_writeable_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_writeable_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_writeable_slave avs_s0_writedata writedata Input DATA_WIDTH
add_interface_port avalon_writeable_slave avs_s0_chipselect chipselect Input 1
add_interface_port avalon_writeable_slave avs_s0_write_n write_n Input 1
add_interface_port avalon_writeable_slave avs_s0_address address Input 2
set_interface_assignment avalon_writeable_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_writeable_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_writeable_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_writeable_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock ""
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit rddata rddata Output DATA_WIDTH
add_interface_port conduit update_avail update_avail Output 1
add_interface_port conduit read_rst read_rst Input 1

