#ifndef _ALTERA_FPGAME_HPS_H_
#define _ALTERA_FPGAME_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'fpgame_soc' in
 * file '../fpgame_soc.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'h2f_vram_interface_0', class 'h2f_vram_interface'
 * The macros are prefixed with 'H2F_VRAM_INTERFACE_0_'.
 * The prefix is the slave descriptor.
 */
#define H2F_VRAM_INTERFACE_0_COMPONENT_TYPE h2f_vram_interface
#define H2F_VRAM_INTERFACE_0_COMPONENT_NAME h2f_vram_interface_0
#define H2F_VRAM_INTERFACE_0_BASE 0x0
#define H2F_VRAM_INTERFACE_0_SPAN 65536
#define H2F_VRAM_INTERFACE_0_END 0xffff

/*
 * Macros for device 'input_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'INPUT_PIO_'.
 * The prefix is the slave descriptor.
 */
#define INPUT_PIO_COMPONENT_TYPE altera_avalon_pio
#define INPUT_PIO_COMPONENT_NAME input_pio
#define INPUT_PIO_BASE 0x0
#define INPUT_PIO_SPAN 16
#define INPUT_PIO_END 0xf
#define INPUT_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define INPUT_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define INPUT_PIO_CAPTURE 0
#define INPUT_PIO_DATA_WIDTH 16
#define INPUT_PIO_DO_TEST_BENCH_WIRING 0
#define INPUT_PIO_DRIVEN_SIM_VALUE 0
#define INPUT_PIO_EDGE_TYPE NONE
#define INPUT_PIO_FREQ 50000000
#define INPUT_PIO_HAS_IN 1
#define INPUT_PIO_HAS_OUT 0
#define INPUT_PIO_HAS_TRI 0
#define INPUT_PIO_IRQ_TYPE NONE
#define INPUT_PIO_RESET_VALUE 0

/*
 * Macros for device 'cpu_wr_busy_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'CPU_WR_BUSY_PIO_'.
 * The prefix is the slave descriptor.
 */
#define CPU_WR_BUSY_PIO_COMPONENT_TYPE altera_avalon_pio
#define CPU_WR_BUSY_PIO_COMPONENT_NAME cpu_wr_busy_pio
#define CPU_WR_BUSY_PIO_BASE 0x10
#define CPU_WR_BUSY_PIO_SPAN 16
#define CPU_WR_BUSY_PIO_END 0x1f
#define CPU_WR_BUSY_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define CPU_WR_BUSY_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CPU_WR_BUSY_PIO_CAPTURE 0
#define CPU_WR_BUSY_PIO_DATA_WIDTH 1
#define CPU_WR_BUSY_PIO_DO_TEST_BENCH_WIRING 0
#define CPU_WR_BUSY_PIO_DRIVEN_SIM_VALUE 0
#define CPU_WR_BUSY_PIO_EDGE_TYPE NONE
#define CPU_WR_BUSY_PIO_FREQ 50000000
#define CPU_WR_BUSY_PIO_HAS_IN 0
#define CPU_WR_BUSY_PIO_HAS_OUT 1
#define CPU_WR_BUSY_PIO_HAS_TRI 0
#define CPU_WR_BUSY_PIO_IRQ_TYPE NONE
#define CPU_WR_BUSY_PIO_RESET_VALUE 0


#endif /* _ALTERA_FPGAME_HPS_H_ */
