	fpgame_soc u0 (
		.apu_control_export_valid            (<connected-to-apu_control_export_valid>),            //                    apu_control.export_valid
		.apu_control_export_data             (<connected-to-apu_control_export_data>),             //                               .export_data
		.clk_clk                             (<connected-to-clk_clk>),                             //                            clk.clk
		.cpu_wr_busy_export                  (<connected-to-cpu_wr_busy_export>),                  //                    cpu_wr_busy.export
		.h2f_vram_interface_export_wraddr    (<connected-to-h2f_vram_interface_export_wraddr>),    //             h2f_vram_interface.export_wraddr
		.h2f_vram_interface_export_wren      (<connected-to-h2f_vram_interface_export_wren>),      //                               .export_wren
		.h2f_vram_interface_export_wrdata    (<connected-to-h2f_vram_interface_export_wrdata>),    //                               .export_wrdata
		.h2f_vram_interface_export_byteena   (<connected-to-h2f_vram_interface_export_byteena>),   //                               .export_byteena
		.h2f_vram_interface_cpu_vram_wr_irq  (<connected-to-h2f_vram_interface_cpu_vram_wr_irq>),  // h2f_vram_interface_cpu_vram_wr.irq
		.hps_io_hps_io_sdio_inst_CMD         (<connected-to-hps_io_hps_io_sdio_inst_CMD>),         //                         hps_io.hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0          (<connected-to-hps_io_hps_io_sdio_inst_D0>),          //                               .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1          (<connected-to-hps_io_hps_io_sdio_inst_D1>),          //                               .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK         (<connected-to-hps_io_hps_io_sdio_inst_CLK>),         //                               .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2          (<connected-to-hps_io_hps_io_sdio_inst_D2>),          //                               .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3          (<connected-to-hps_io_hps_io_sdio_inst_D3>),          //                               .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0          (<connected-to-hps_io_hps_io_usb1_inst_D0>),          //                               .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1          (<connected-to-hps_io_hps_io_usb1_inst_D1>),          //                               .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2          (<connected-to-hps_io_hps_io_usb1_inst_D2>),          //                               .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3          (<connected-to-hps_io_hps_io_usb1_inst_D3>),          //                               .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4          (<connected-to-hps_io_hps_io_usb1_inst_D4>),          //                               .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5          (<connected-to-hps_io_hps_io_usb1_inst_D5>),          //                               .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6          (<connected-to-hps_io_hps_io_usb1_inst_D6>),          //                               .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7          (<connected-to-hps_io_hps_io_usb1_inst_D7>),          //                               .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK         (<connected-to-hps_io_hps_io_usb1_inst_CLK>),         //                               .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP         (<connected-to-hps_io_hps_io_usb1_inst_STP>),         //                               .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR         (<connected-to-hps_io_hps_io_usb1_inst_DIR>),         //                               .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT         (<connected-to-hps_io_hps_io_usb1_inst_NXT>),         //                               .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX         (<connected-to-hps_io_hps_io_uart0_inst_RX>),         //                               .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX         (<connected-to-hps_io_hps_io_uart0_inst_TX>),         //                               .hps_io_uart0_inst_TX
		.input_pio_export                    (<connected-to-input_pio_export>),                    //                      input_pio.export
		.memory_mem_a                        (<connected-to-memory_mem_a>),                        //                         memory.mem_a
		.memory_mem_ba                       (<connected-to-memory_mem_ba>),                       //                               .mem_ba
		.memory_mem_ck                       (<connected-to-memory_mem_ck>),                       //                               .mem_ck
		.memory_mem_ck_n                     (<connected-to-memory_mem_ck_n>),                     //                               .mem_ck_n
		.memory_mem_cke                      (<connected-to-memory_mem_cke>),                      //                               .mem_cke
		.memory_mem_cs_n                     (<connected-to-memory_mem_cs_n>),                     //                               .mem_cs_n
		.memory_mem_ras_n                    (<connected-to-memory_mem_ras_n>),                    //                               .mem_ras_n
		.memory_mem_cas_n                    (<connected-to-memory_mem_cas_n>),                    //                               .mem_cas_n
		.memory_mem_we_n                     (<connected-to-memory_mem_we_n>),                     //                               .mem_we_n
		.memory_mem_reset_n                  (<connected-to-memory_mem_reset_n>),                  //                               .mem_reset_n
		.memory_mem_dq                       (<connected-to-memory_mem_dq>),                       //                               .mem_dq
		.memory_mem_dqs                      (<connected-to-memory_mem_dqs>),                      //                               .mem_dqs
		.memory_mem_dqs_n                    (<connected-to-memory_mem_dqs_n>),                    //                               .mem_dqs_n
		.memory_mem_odt                      (<connected-to-memory_mem_odt>),                      //                               .mem_odt
		.memory_mem_dm                       (<connected-to-memory_mem_dm>),                       //                               .mem_dm
		.memory_oct_rzqin                    (<connected-to-memory_oct_rzqin>),                    //                               .oct_rzqin
		.ppu_bgcolor_export                  (<connected-to-ppu_bgcolor_export>),                  //                    ppu_bgcolor.export
		.ppu_bgscroll_export                 (<connected-to-ppu_bgscroll_export>),                 //                   ppu_bgscroll.export
		.ppu_enable_export                   (<connected-to-ppu_enable_export>),                   //                     ppu_enable.export
		.ppu_fgscroll_export                 (<connected-to-ppu_fgscroll_export>),                 //                   ppu_fgscroll.export
		.hps_0_f2h_sdram0_data_address       (<connected-to-hps_0_f2h_sdram0_data_address>),       //          hps_0_f2h_sdram0_data.address
		.hps_0_f2h_sdram0_data_burstcount    (<connected-to-hps_0_f2h_sdram0_data_burstcount>),    //                               .burstcount
		.hps_0_f2h_sdram0_data_waitrequest   (<connected-to-hps_0_f2h_sdram0_data_waitrequest>),   //                               .waitrequest
		.hps_0_f2h_sdram0_data_readdata      (<connected-to-hps_0_f2h_sdram0_data_readdata>),      //                               .readdata
		.hps_0_f2h_sdram0_data_readdatavalid (<connected-to-hps_0_f2h_sdram0_data_readdatavalid>), //                               .readdatavalid
		.hps_0_f2h_sdram0_data_read          (<connected-to-hps_0_f2h_sdram0_data_read>)           //                               .read
	);

